"""initial_schema_with_wealth

Revision ID: 3a036e0f855f
Revises: 
Create Date: 2026-04-18 22:05:46.277428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a036e0f855f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wealth_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('native_balance', sa.Float(), nullable=False),
    sa.Column('fx_to_eur', sa.Float(), nullable=False),
    sa.Column('allocation_bucket', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wealth_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('related_scenario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wealth_fire_scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('annual_income_eur', sa.Float(), nullable=False),
    sa.Column('annual_expenses_eur', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('tax_rate_pct', sa.Float(), nullable=False),
    sa.Column('inflation_pct', sa.Float(), nullable=False),
    sa.Column('withdrawal_rate_pct', sa.Float(), nullable=False),
    sa.Column('profile_scope', sa.String(), nullable=False),
    sa.Column('target_retirement_age', sa.Integer(), nullable=False),
    sa.Column('post_retirement_work_income_eur', sa.Float(), nullable=True),
    sa.Column('capital_strategy', sa.String(), nullable=True),
    sa.Column('starting_portfolio_eur', sa.Float(), nullable=False),
    sa.Column('on_trajectory', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wealth_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('net_worth_eur', sa.Float(), nullable=False),
    sa.Column('assets_eur', sa.Float(), nullable=False),
    sa.Column('liabilities_eur', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wealth_mortgages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('annual_rate_pct', sa.Float(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(), nullable=False),
    sa.Column('mortgage_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wealth_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('wealth_portfolio_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('allocation_bucket', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('native_amount', sa.Float(), nullable=False),
    sa.Column('fx_to_eur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wealth_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wealth_portfolio_lines')
    op.drop_table('wealth_mortgages')
    op.drop_table('wealth_snapshots')
    op.drop_table('wealth_fire_scenarios')
    op.drop_table('wealth_decisions')
    op.drop_table('wealth_accounts')
    # ### end Alembic commands ###
