#!/usr/bin/env bash
set -euo pipefail

# Render Environment Configuration Helper
# Guides you through entering DATABASE_URL and frontend URL,
# then prints ready-to-paste environment variable assignments for Render.

echo "=== Render Free Deploy - Environment Setup ==="
echo ""
echo "This script will help you configure environment variables for your Render deployment."
echo ""

# DATABASE_URL
read -p "Enter your Neon DATABASE_URL (postgresql://...): " DATABASE_URL
if [[ -z "$DATABASE_URL" ]]; then
    echo "Error: DATABASE_URL cannot be empty."
    exit 1
fi

# FRONTEND_URL
echo ""
echo "After deploying frontend to Vercel, you'll get a URL like:"
echo "  https://my-app.vercel.app"
echo ""
read -p "Enter your frontend URL from Vercel: " FRONTEND_URL
if [[ -z "$FRONTEND_URL" ]]; then
    echo "Error: FRONTEND_URL cannot be empty."
    exit 1
fi

# Remove trailing slashes
FRONTEND_URL="${FRONTEND_URL%/}"

# CORS_ORIGINS
CORS_ORIGINS="$FRONTEND_URL"

echo ""
echo "=== Render Environment Variables ==="
echo ""
echo "Copy and paste these into your Render dashboard (Settings > Environment):"
echo ""
echo "DATABASE_URL=$DATABASE_URL"
echo "FRONTEND_URL=$FRONTEND_URL"
echo "CORS_ORIGINS=$CORS_ORIGINS"
echo "COOKIE_SECURE=true"
echo ""
echo "JWT_SECRET will be auto-generated by Render if not set."
echo ""
echo "Next steps:"
echo "  1. Go to Render dashboard for 'wealthmanagement-api'"
echo "  2. Settings > Environment"
echo "  3. Add/update the variables above"
echo "  4. Trigger redeploy"
echo "  5. Verify health: curl https://<your-backend>.onrender.com/health"
echo ""
